apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: ai-service
        image: prasad890/store-ai-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: USE_AZURE_OPENAI
          value: "False"
        - name: AZURE_OPENAI_DALLE_DEPLOYMENT_NAME 
          value: "dall-e-3"
        - name: AZURE_OPENAI_DALLE_ENDPOINT
          value: "https://store-app.openai.azure.com"
        - name: OPENAI_API_KEY 
          value: "OPENAI_API_KEY_PLACEHOLDER_use_your_own_key"
        - name: OPENAI_ORG_ID 
          value: "OPENAI_ORG_ID_PLACEHOLDER_use_your_own_org_id"
        - name: AZURE_OPENAI_API_VERSION
          value: "2024-02-15-preview"
        - name: AZURE_OPENAI_API_KEY
          value: "AZURE_OPENAI_API_KEY_PLACEHOLDER_use_your_own_key"
        - name: USE_AZURE_AD
          value: "False"
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 128Mi
        startupProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 60
          failureThreshold: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 3
          failureThreshold: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 3
          failureThreshold: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5001
    targetPort: 5001
  selector:
    app: ai-service