# ai-service-vault.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-service
  namespace: application

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "ai-service"
        vault.hashicorp.com/agent-inject-secret-openai.env: "kv/data/ai-service"
        vault.hashicorp.com/agent-inject-template-openai.env: |
          #!/bin/sh
          {{- with secret "kv/data/ai-service" -}}
          export OPENAI_API_KEY="{{ .Data.data.openai_api_key }}"
          export OPENAI_ORG_ID="{{ .Data.data.openai_org_id }}"
          export AZURE_OPENAI_API_KEY="{{ .Data.data.azure_openai_api_key }}"
          {{- end -}}
    spec:
      serviceAccountName: ai-service
      containers:
      - name: ai-service
        image: prasad890/store-ai-service:latest
        command: ["/bin/sh"]
        args: 
        - -c
        - |
          source /vault/secrets/openai.env
          exec python app.py
        ports:
        - containerPort: 5001
        env:
        - name: USE_AZURE_OPENAI
          value: "False"
        - name: AZURE_OPENAI_DALLE_DEPLOYMENT_NAME 
          value: "dall-e-3"
        - name: AZURE_OPENAI_DALLE_ENDPOINT
          value: "https://storeapp.openai.azure.com"
        - name: AZURE_OPENAI_API_VERSION
          value: "2024-02-15-preview"
        - name: USE_AZURE_AD
          value: "False"
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 128Mi
        startupProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 60
          failureThreshold: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 3
          failureThreshold: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 3
          failureThreshold: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: application
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5001
    targetPort: 5001
  selector:
    app: ai-service