# infrastructure/argocd/applications/ai-service-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ai=591234613960.dkr.ecr.us-east-1.amazonaws.com/ai-service
    argocd-image-updater.argoproj.io/ai.update-strategy: semver
    argocd-image-updater.argoproj.io/ai.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+-.+$
    argocd-image-updater.argoproj.io/ai.ignore-tags: latest, dev, staging
    argocd-image-updater.argoproj.io/write-back-method: argocd 
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd-notifications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: ai-service
    app.kubernetes.io/part-of: store-app
    deployment-strategy: canary
spec:
  project: default
  
  source:
    repoURL: https://github.com/prasad-moru/GenAiStoreApp.git
    targetRevision: main
    path: helm-charts/ai-service
    helm:
      releaseName: ai-service
      valueFiles:
        - values.yaml
      parameters:
        - name: serviceAccount.name
          value: ai-service
          forceString: true       
  
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas
  
  revisionHistoryLimit: 10